name: 'AzGather - Gather Azure environment info'
description: 'Gather environment info from Azure and store them as systems environment variables in runner'
branding:
  icon: 'search'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Download AzUtilities
      shell: pwsh
      run: |
        Write-Output '::group::Download AzUtilities'
        $env:PSModulePath -split $([System.IO.Path]::PathSeparator)
        $InstallPath = $env:PSModulePath -split $([System.IO.Path]::PathSeparator) | Select-Object -First 1
        if (! (Test-Path -Path $InstallPath)){
            try {
                Write-Output "$InstallPath not found, creating"
                New-Item -Path $InstallPath -ItemType "directory" -Force | Out-Null
            } catch {
                throw "$InstallPath creating failed"
            }
        }
        Write-Output "InstallPath: $InstallPath"

        New-Item -Path "$InstallPath\Utils" -ItemType "directory" -Force | Out-Null
        Invoke-WebRequest -OutFile "$InstallPath\Utils\Utils.psm1" -Uri "https://raw.githubusercontent.com/equinor/AzUtilities/main/Modules/Utils/Utils.psm1"
        Invoke-WebRequest -OutFile "$InstallPath\Utils\Utils.psd1" -Uri "https://raw.githubusercontent.com/equinor/AzUtilities/main/Modules/Utils/Utils.psd1"

    - name: AzGather
      shell: pwsh
      run: |
        . "$env:GITHUB_ACTION_PATH\Scripts\main.ps1"
